### PR TITLE
Added env sample file, app module now loads env file

### PR DESCRIPTION
**Pull request by phulsechinmay**
Just setting up basic env file and config loading in AppModule.

This uses the basic nestjs config functionality. There are other packages out there that can give us more. @geooot Do you have a recommendation for a specific one, or should we stick with this?

### CODE REVIEW

**Comment by geooot** [comment]
@phulsechinmay As long as it lets us choose an env file to use for production versus dev I think this should work. Can you think of any other features we would need?

**Comment by phulsechinmay** [comment]
@geooot I saw a package that also uses a .env.sample file which specifies all the required keys (without values of course), and then checks if all those keys are present in the env file it's loading. 

That seems like useful functionality, but it's not a core nestjs package, I believe it's external.

**Comment by geooot** [comment]
@phulsechinmay You could try to use the external one if you like. But I think it should definitely be wrapped as a nest Module

**Comment by phulsechinmay** [comment]
@geooot This loader has a 'safe' mode that outputs to the console, all the keys that are undefined.

* Also added support for different env files for different modes through use of NODE_ENV
   * Env files are called `.env.[dev|test|production]

Let me know if anything else is needed or this is good to go.

**Pull request merged**
