### PR TITLE
Google oauth

### PR DESCRIPTION
**Pull request by phulsechinmay**
Linked to #11.

### CODE REVIEW

**Comment by phulsechinmay** [comment]
@geooot There wasn't a great way of propagating the redirect param across requests for Google auth. So I made the following changes:
* The index view takes the redirect as a param for ejs and renders it into the button link `href`s
* The google login endpoint saves the redirect in `req.session` and the callback endpoint uses it and clears it

If you can think of a better way to make the redirect param persist across requests, we can try that out too.

**Comment by phulsechinmay** [comment]
@geooot The callback URL is the endpoints `/auth/login/google/callback`, so if you're running it on `localhost:3000`, the URL would be `http://localhost:3000/auth/login/google/callback`. 

Also, for the case you mentioned, the strategy checks if they have signed up with another authentication provider (either Email or Facebook), so we can throw a custom error and show an appropriate message for that. Do you want that to be added to this PR or make a new issue for it?

**Comment by geooot** [comment]
@phulsechinmay let's have that error case handled on this PR

**Comment by phulsechinmay** [comment]
@geooot I added error handling for the case where authorization providers differ. 

Also added a case where it shows an error if the user with the given email does not exist (when using `EmailAndPassword`). Can remove that if we think that's unnecessary info / security risk.

Also, I was working on Facebook oauth in another branch but I ended up making the error handling changes in that branch by mistake. So I had to merge them. This PR closes #11 now.

**Pull request merged**
