### PR TITLE
Signup flow

### LINKED ISSUE #9: Create Signup Flow (basic UI; full backend implementation)
Signup Flow for Email and Password

### PR DESCRIPTION
**Pull request by phulsechinmay**
Closes #9 
* Added controller and service for email-password signup
* Changed UserAuthService to throw NestJS exception filters that can be directly propagated into HTTP errors

### CODE REVIEW

**Comment by phulsechinmay** [comment]
@geooot Didn't know how basic the UI should be, might need to lay out how we'll be handling errors like user conflicts and more on the front-end

**Comment by phulsechinmay** [comment]
@geooot 
NestJS lets us directly validate DTOs and directly returns 400 errors with appropriate error messages if validation fails. I've added that in. Are we good with that or do we wanna do custom validation?

**Comment by geooot** [comment]
@phulsechinmay Just committed an eslint change to get rid of that warning. Before we merge this, can we render an error message for the 400 error as well? Right now it returns the raw JSON which includes the password in clear text

image

**Comment by phulsechinmay** [comment]
@geooot 
Oof that is bad. Should we render a view for it? We can set up global filters for 4XX & 5XX error codes that render views accordingly

**Comment by geooot** [comment]
@phulsechinmay for the signup form validation errors specifically we should just return the signup page again with the error. Kinda like the email already exists error: 
image

We need to have a similar error messaging for
- invalid email
- confirmed password doesn't match the password entered
- fields are left blank

**Comment by phulsechinmay** [comment]
@geooot I added view-based error handling. Let me know what you think

**Pull request merged**
